#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on:
  workflow_dispatch:  
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  SSH_ACTIONS: false
  UPLOAD_FIRMWARE: false
  UPLOAD_DOCKER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Install depends
      run: |
          docker rmi `docker images -q`
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone $TZ
    - name: Clone Lean's openwrt
      run: |
          git clone https://github.com/coolsnowwolf/lede
          
    - name: Install feeds & Make config
      run: |
         [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
         chmod +x $DIY_SH
         $GITHUB_WORKSPACE/$DIY_SH
          
    - name: Compile openwrt
      run: |
          cd lede
          make download -j8
          make -j$(nproc) || make -j1 V=s
        
    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      run: |
        cd lede/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
        
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
      
    - name: Build firmware
      run: |
        cp lede/bin/targets/*/*/*.tar.gz ./openwrt
        sudo ./make -d
        cp lede/.config out/config.seed
        
        cd out
        i=0
        kernels=("4.18.7" "4.19.106" "5.4.43")
        for x in ${kernels[*]}; do
          cd $x
          filename=$(ls)
          filename=${filename%.*}
          gzip *.img
          cd ../
          echo "firmware_$x=$filename" >> $GITHUB_ENV
        done
          
    - name: Upload firmware @ kernel 4.18.7
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.firmware_1 }}
        path: out/4.18.7
      
    - name: Upload firmware @ kernel 4.19.106
      uses: actions/upload-artifact@main     
      with:
        name: ${{ env.firmware_2 }}
        path: out/4.19.106
      
    - name: Upload firmware @ kernel 5.4.43
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.firmware_3 }}
        path: out/5.4.43

    - name: Upload config file
      uses: actions/upload-artifact@main
      with:
        name: config
        path: out/config.seed
