
name: clean artifacts

on:
  push:
    paths: 
      - '.github/workflows/cleanup.yml'
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 5days # Setting this to 0 will delete all artifacts 
